from datetime import datetime

tracks = [
    {"name": "SNES Mario Circuit 3", "category": "snes_dlc"},
    {"name": "SNES Bowser Castle 3", "category": "snes_dlc"},
    {"name": "SNES Donut Plains 3", "category": "snes_dlc"},
    {"name": "SNES Rainbow Road", "category": "snes_dlc"},
    {"name": "N64 Kalimari Desert", "category": "retro"},
    {"name": "N64 Toad's Turnpike", "category": "retro"},
    {"name": "N64 Choco Mountain", "category": "retro"},
    {"name": "N64 Royal Raceway", "category": "retro"},
    {"name": "N64 Yoshi Valley", "category": "retro"},
    {"name": "N64 Rainbow Road", "category": "retro"},
    {"name": "GBA Riverside Park", "category": "handheld"},
    {"name": "GBA Mario Circuit", "category": "handheld"},
    {"name": "GBA Boo Lake", "category": "handheld"},
    {"name": "GBA Cheese Land", "category": "handheld"},
    {"name": "GBA Sky Garden", "category": "handheld"},
    {"name": "GBA Sunset Wilds", "category": "handheld"},
    {"name": "GBA Snow Land", "category": "handheld"},
    {"name": "GBA Ribbon Road", "category": "handheld"},
    {"name": "GCN Baby Park", "category": "retro"},
    {"name": "GCN Dry Dry Desert", "category": "retro"},
    {"name": "GCN Daisy Cruiser", "category": "retro"},
    {"name": "GCN Waluigi Stadium", "category": "retro"},
    {"name": "GCN Sherbet Land", "category": "retro"},
    {"name": "GCN Yoshi Circuit", "category": "retro"},
    {"name": "GCN DK Mountain", "category": "retro"},
    {"name": "DS Cheep Cheep Beach", "category": "handheld"},
    {"name": "DS Waluigi Pinball", "category": "handheld"},
    {"name": "DS Shroom Ridge", "category": "handheld"},
    {"name": "DS Tick-Tock Clock", "category": "handheld"},
    {"name": "DS Mario Circuit", "category": "handheld"},
    {"name": "DS Wario Stadium", "category": "handheld"},
    {"name": "DS Peach Gardens", "category": "handheld"},
    {"name": "Wii Moo Moo Meadows", "category": "retro"},
    {"name": "Wii Mushroom Gorge", "category": "retro"},
    {"name": "Wii Coconut Mall", "category": "retro"},
    {"name": "Wii DK Summit", "category": "retro"},
    {"name": "Wii Wario's Gold Mine", "category": "retro"},
    {"name": "Wii Daisy Circuit", "category": "retro"},
    {"name": "Wii Koopa Cape", "category": "retro"},
    {"name": "Wii Maple Treeway", "category": "retro"},
    {"name": "Wii Grumble Volcano", "category": "retro"},
    {"name": "Wii Moonview Highway", "category": "retro"},
    {"name": "Wii Rainbow Road", "category": "retro"},
    {"name": "3DS Toad Circuit", "category": "handheld"},
    {"name": "3DS Music Park", "category": "handheld"},
    {"name": "3DS Rock Rock Mountain", "category": "handheld"},
    {"name": "3DS Piranha Plant Slide", "category": "handheld"},
    {"name": "3DS Neo Bowser City", "category": "handheld"},
    {"name": "3DS DK Jungle", "category": "handheld"},
    {"name": "3DS Rosalina's Ice World", "category": "handheld"},
    {"name": "3DS Rainbow Road", "category": "handheld"},
    {"name": "Mario Kart Stadium", "category": "base"},
    {"name": "Water Park", "category": "base"},
    {"name": "Sweet Sweet Canyon", "category": "base"},
    {"name": "Twomp Ruins", "category": "base"},
    {"name": "Mario Circuit", "category": "base"},
    {"name": "Toad Harbor", "category": "base"},
    {"name": "Twisted Mansion", "category": "base"},
    {"name": "Shy Guy Falls", "category": "base"},
    {"name": "Sunshine Airport", "category": "base"},
    {"name": "Dolphin Shoals", "category": "base"},
    {"name": "Electrodrome", "category": "snes_dlc"},
    {"name": "Mount Wario", "category": "base"},
    {"name": "Cloudtop Cruise", "category": "base"},
    {"name": "Bone-Dry Dunes", "category": "base"},
    {"name": "Bowser's Castle", "category": "base"},
    {"name": "Rainbow Road", "category": "base"},
    {"name": "Excitebike Arena", "category": "snes_dlc"},
    {"name": "Dragon Driftway", "category": "snes_dlc"},
    {"name": "Mute City", "category": "snes_dlc"},
    {"name": "Ice Ice Outpost", "category": "snes_dlc"},
    {"name": "Hyrule Circuit", "category": "snes_dlc"},
    {"name": "Wild Woods", "category": "snes_dlc"},
    {"name": "Animal Crossing", "category": "snes_dlc"},
    {"name": "Super Bell Subway", "category": "snes_dlc"},
    {"name": "Big Blue", "category": "snes_dlc"},
    {"name": "Tour New York Minute", "category": "tour"},
    {"name": "Tour Tokyo Blur", "category": "tour"},
    {"name": "Tour Paris Promenade", "category": "tour"},
    {"name": "Tour London Loop", "category": "tour"},
    {"name": "Tour Vancouver Velocity", "category": "tour"},
    {"name": "Tour Los Angeles Laps", "category": "tour"},
    {"name": "Merry Mountain", "category": "snes_dlc"},
    {"name": "Tour Berlin Byways", "category": "tour"},
    {"name": "Ninja Hideaway", "category": "snes_dlc"},
    {"name": "Tour Sidney Sprint", "category": "tour"},
    {"name": "Tour Singapore Speedway", "category": "tour"},
    {"name": "Tour Amsterdam Drift", "category": "tour"},
    {"name": "Tour Bangkok Rush", "category": "tour"},
    {"name": "Sky-High Sundae", "category": "snes_dlc"},
    {"name": "Piranha Plant Cove", "category": "snes_dlc"},
    {"name": "Yoshi's Island", "category": "snes_dlc"},
    {"name": "Tour Athens Dash", "category": "tour"},
    {"name": "Tour Rome Avanti", "category": "tour"},
    {"name": "Squeaky Clean Sprint", "category": "snes_dlc"},
    {"name": "Tour Madrid Drive", "category": "tour"},
]


def placement_to_string(placement: int):
    strings = ["1st", "2nd", "3rd", "4th", "5th", "6th", "7th", "8th", "9th", "10th", "11th", "12th"]

    return strings[placement - 1]



def convert_to_isoformat(date_str):
    date_obj = datetime.strptime(date_str, '%d-%m-%Y')
    return date_obj.date().isoformat()